runtime: python27
threadsafe: true

handlers:
- url: /(.*\.css)
  mime_type: text/css
  static_files: css/\1
  upload: css/(.*\.css)

# site root
- url: /
  static_files: index.html
  upload: index.html
